development:
  adapter: postgresql
  encoding: unicode
  database: ratings_development
  pool: 5

#test:
#  adapter: sqlite3
#  database: db/test.sqlite3
#  pool: 5
#  timeout: 5000

production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: caveat_production
  pool: 5
  username: adamb
